### ISSUE TITLE
MLab's first results is often a city half way around the world

### ISSUE THREAD

**Issue by mmcev106** [apenwarr/blip#12]
I live in the US, but the first city returned by MLab is often in Europe.  Removing the "policy=all" from the url seems to always correctly return the closest server to me.  Would it make sense to remove that parameter?

**Comment by apenwarr** [comment]
Right now blip downloads the complete list of all servers, then tries to choose one using its own algorithm.  It shouldn't be picking one in Europe unless something weird is happening.  It also shouldn't just be picking the first one it sees from MLab - it's supposed to be sorting them.

To make matters a little more complicated, blip tries to choose the *second* slowest server.  It intentionally doesn't want to use one too close to you, since we want to test actual "Internet" latency rather than "latency to some artificially nearby point."  So it's possibly doing what's intended here...

**Comment by mmcev106** [comment]
Blip still seems to go through periods of favoring overseas servers for me.  I'm in Nashville, TN, and in the following video you can see only 2 US servers were loaded out of 7 refreshes:

https://youtu.be/Mo9j6OTVRzU

I can't justify the time to troubleshoot it alone, but let me know if I can provide any debugging info.

**Comment by gwillen** [comment]
I've been noticing the same thing, e.g. testing just now from California, I got USA three times, Tunisia once, Czech Republic once, and Canada once. I would call that 4/6 reasonable servers except for some reason the Canada one was giving all red blips.

**Comment by apenwarr** [comment]
should be fixed now!
