### ISSUE TITLE
After changing tab/window focus, there is a gap in the graph

### ISSUE THREAD

**Issue by jmoseley** [apenwarr/blip#15]
Changing tab focus causes a gap in the graph.

https://user-images.githubusercontent.com/4382100/199757623-de135dcb-ab43-44ab-be6c-6a81aaa364b4.mov

**Comment by Joshfindit** [comment]
My first instinct is to say that this is due to the browsers now de-prioritizing tabs that are not in the foreground.

With the rise of webpage complexity and user pushback about poor system UX when they are bogged-down by tabs, it's now standard for browsers to deprioritize, increase delays, or even pause tabs completely. Especially Javascript.

**Comment by jmoseley** [comment]
As far as I can tell, it does not stop pinging, the graph simply draws a gap. The size of the gap is the same regardless of how long the tab is out of focus.

**Comment by apenwarr** [comment]
This artifact occurs, I think, because your browser really does stop letting blip generate network requests a little while after the tab loses visibility (probably to prevent battery wastage, trackers, etc). This behaviour might be browser dependent but seems to be widespread on the devices I've tested on.

You should be able to confirm this by opening the javascript debugger and looking at the rate of error message generation while the blip pane is visible, vs when it's not.

Anyway, I think the behaviour correctly represents what's going on in terms of network traffic.

**Comment by jmoseley** [comment]
Yes I think you are right. Likely a challenging thing to overcome.
